from enum import Enum

class PaymentGateways(Enum):

    CHEAPPAYMENTGAYEWAY = 20
    EXPENSIVEPAYMENTGAYEWAY = 21
    PREMIUMPAYMENTGAYEWAY = 500

class StripAPI(Enum):
    STRIPE_PUBLIC_KEY = "pk_test_51IBtOyFLebDPRWT7jktz8sVttaQYbGtu8qezuhSxGPCWVMP5fLII3aUApvJ5SUDLNPAHtjuVxFqVdgMuKeGWiFda00SxQs2K0m"
    STRIPE_SECRET_KEY = "sk_test_51IBtOyFLebDPRWT7ooan25XXpHQvFmpY6oUx5GKOGLCAqrUBmKuLfdvWG0YfR5LzPEsaVSwGFgUmVFzdGBXGFFCV00lcgxR3jf"
